const K={t:"fs_tasks",s:"fs_schedule",n:"fs_notes",h:"fs_habits",p:"fs_pomo",c:"fs_pomo_cfg"};
const S={prompt:null,timer:{total:1500,left:1500,id:null},sw:{run:false,ms:0,start:0,id:null,laps:[]},po:{run:false,phase:"focus",left:1500,id:null,cycles:0}};
const DAYS=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
const WORLD=[["Jakarta","Asia/Jakarta"],["Tokyo","Asia/Tokyo"],["London","Europe/London"],["New York","America/New_York"]];
const $=(s)=>document.querySelector(s);
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const uid=()=>crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const fDate=(d=new Date())=>new Intl.DateTimeFormat("id-ID",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(d);
const fTime=(z="Asia/Jakarta",s=true)=>new Intl.DateTimeFormat("en-GB",{timeZone:z,hour:"2-digit",minute:"2-digit",second:s?"2-digit":undefined,hour12:false}).format(new Date());
const fMs=(ms,t=false)=>{ms=Math.max(0,ms);let s=Math.floor(ms/1e3),h=String(Math.floor(s/3600)).padStart(2,"0"),m=String(Math.floor(s%3600/60)).padStart(2,"0"),x=String(s%60).padStart(2,"0");return t?`${h}:${m}:${x}.${Math.floor(ms%1e3/100)}`:`${h}:${m}:${x}`};
const fMin=(s)=>`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;
const empty=(m)=>`<div class="item"><div class="copy"><strong>Belum ada data</strong><p class="muted">${m}</p></div></div>`;
function nav(){let p=location.pathname.split("/").pop()||"index.html";document.querySelectorAll(".nav-link").forEach(a=>{let on=a.dataset.nav===p;a.classList.toggle("active",on);if(on)a.setAttribute("aria-current","page");else a.removeAttribute("aria-current")})}
function score(){let t=read(K.t,[]),h=read(K.h,[]),p=read(K.p,{done:0}),done=t.filter(x=>x.done).length,hit=h.reduce((a,b)=>a+b.days.filter(Boolean).length,0),v=Math.min(100,done*12+hit*2+(p.done||0)*8),el=$("#focus-chip");if(el)el.textContent=`Focus score ${v}`}
function topbar(){let d=$("#today-chip");if(d)d.textContent=fDate();score()}
function install(){let b=$("#install-app");if(!b)return;addEventListener("beforeinstallprompt",e=>{e.preventDefault();S.prompt=e;b.disabled=false});b.onclick=async()=>{if(!S.prompt)return;S.prompt.prompt();await S.prompt.userChoice;S.prompt=null;b.disabled=true}}
function sw(){if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("sw.js"))}
function dash(){let t=read(K.t,[]),s=read(K.s,[]).sort((a,b)=>a.time.localeCompare(b.time)),h=read(K.h,[]),p=read(K.p,{done:0});
  setInterval(()=>{$("#hero-time").textContent=fTime();$("#hero-date").textContent=fDate()},1000);$("#hero-time").textContent=fTime();$("#hero-date").textContent=fDate();
  $("#dashboard-task-complete").textContent=t.filter(x=>x.done).length;$("#dashboard-pomodoro-count").textContent=p.done||0;
  $("#dashboard-task-list").innerHTML=t.slice(0,3).map(x=>`<div class="item task ${x.done?"done":""}"><div class="copy"><strong>${x.title}</strong><p class="muted">${x.note||"Tanpa catatan"}</p></div><span class="badge priority-${x.priority}">${x.priority}</span></div>`).join("")||empty("Tambahkan task prioritas.");
  $("#dashboard-schedule-list").innerHTML=s.slice(0,4).map(x=>`<div class="item"><div class="copy"><strong>${x.title}</strong><p class="muted">${x.note||x.cat}</p></div><span class="badge">${x.time}</span></div>`).join("")||empty("Atur agenda hari ini.");
  $("#dashboard-habits").innerHTML=h.slice(0,3).map(x=>`<div class="item"><div class="copy"><strong>${x.name}</strong><p class="muted">${x.target}</p></div><span class="badge">${x.days.filter(Boolean).length}/7</span></div>`).join("")||empty("Tambahkan satu habit inti.");
}
function clockPage(){const tick=()=>{$("#clock-main-time").textContent=fTime();$("#clock-main-date").textContent=fDate();$("#world-clock-list").innerHTML=WORLD.map(([c,z])=>`<div class="item"><div class="copy"><strong>${c}</strong><p class="muted">${z}</p></div><span class="badge">${fTime(z,false)}</span></div>`).join("")};tick();setInterval(tick,1000);let s=read(K.s,[]).sort((a,b)=>a.time.localeCompare(b.time));$("#clock-schedule-preview").innerHTML=s.map(x=>`<div class="item"><div class="copy"><strong>${x.title}</strong><p class="muted">${x.cat}</p></div><span class="badge">${x.time}</span></div>`).join("")||empty("Belum ada agenda.");}
function stopwatch(){const r=()=>{$("#stopwatch-display").textContent=fMs(S.sw.ms,true);$("#lap-list").innerHTML=S.sw.laps.map((x,i)=>`<div class="item"><strong>Lap ${S.sw.laps.length-i}</strong><span class="badge">${fMs(x,true)}</span></div>`).join("")||empty("Jalankan stopwatch lalu tekan lap.");$("#stopwatch-start").textContent=S.sw.run?"Stop":"Start"};$("#stopwatch-start").onclick=()=>{if(S.sw.run){S.sw.run=false;clearInterval(S.sw.id);return r()}S.sw.run=true;S.sw.start=Date.now()-S.sw.ms;S.sw.id=setInterval(()=>{S.sw.ms=Date.now()-S.sw.start;r()},100);r()};$("#stopwatch-lap").onclick=()=>{if(!S.sw.run)return;S.sw.laps.unshift(S.sw.ms);r()};$("#stopwatch-reset").onclick=()=>{clearInterval(S.sw.id);S.sw={run:false,ms:0,start:0,id:null,laps:[]};r()};r()}
function timer(){const rs=()=>$("#timer-display").textContent=fMin(S.timer.left),stop=()=>{clearInterval(S.timer.id);S.timer.id=null};$("#timer-presets").innerHTML=[15,25,45,60].map(m=>`<button class="mini" data-m="${m}"><strong>${m} min</strong></button>`).join("");$("#timer-presets").onclick=e=>{let b=e.target.closest("[data-m]");if(!b)return;S.timer.total=S.timer.left=Number(b.dataset.m)*60;stop();rs()};$("#timer-start").onclick=()=>{stop();S.timer.id=setInterval(()=>{if(S.timer.left<=0)return stop();S.timer.left--;rs()},1000)};$("#timer-pause").onclick=stop;$("#timer-reset").onclick=()=>{stop();S.timer.left=S.timer.total;rs()};$("#custom-timer-form").onsubmit=e=>{e.preventDefault();let m=Number($("#custom-timer-minutes").value||0);if(!m)return;S.timer.total=S.timer.left=m*60;stop();rs();e.target.reset()};rs()}
function pomodoro(){let cfg={focus:25,short:5,long:15,rounds:4,...read(K.c,{})},st={done:0,...read(K.p,{done:0})};["focus","short","long","rounds"].forEach(k=>$("#pomodoro-"+k).value=cfg[k]);const setP=p=>{S.po.phase=p;S.po.left=cfg[p==="focus"?"focus":p==="short"?"short":"long"]*60},ren=()=>{$("#pomodoro-display").textContent=fMin(S.po.left);$("#pomodoro-phase").textContent=S.po.phase==="focus"?"Focus session":S.po.phase==="short"?"Short break":"Long break";$("#pomodoro-completed").textContent=st.done;$("#pomodoro-next-break").textContent=Math.max(1,cfg.rounds-(S.po.cycles%cfg.rounds));$("#pomodoro-start").textContent=S.po.run?"Pause":"Start"},stop=()=>{clearInterval(S.po.id);S.po.run=false;ren()},next=()=>{if(S.po.phase==="focus"){S.po.cycles++;st.done++;write(K.p,st);score();setP(S.po.cycles%cfg.rounds===0?"long":"short")}else setP("focus");ren()};
  $("#pomodoro-start").onclick=()=>{if(S.po.run)return stop();S.po.run=true;S.po.id=setInterval(()=>{if(S.po.left<=0)return next();S.po.left--;ren()},1000);ren()};$("#pomodoro-skip").onclick=next;$("#pomodoro-reset").onclick=()=>{stop();S.po.cycles=0;setP("focus");ren()};$("#pomodoro-settings").onsubmit=e=>{e.preventDefault();cfg={focus:+$("#pomodoro-focus").value,short:+$("#pomodoro-short").value,long:+$("#pomodoro-long").value,rounds:+$("#pomodoro-rounds").value};write(K.c,cfg);stop();setP("focus");ren()};setP("focus");ren()}
function schedule(){const list=$("#schedule-list"),ren=()=>{let a=read(K.s,[]).sort((x,y)=>x.time.localeCompare(y.time));list.innerHTML=a.map(x=>`<div class="item"><div class="copy"><strong>${x.title}</strong><p class="muted">${x.cat} - ${x.note||"Tanpa catatan"}</p></div><div class="item-actions"><span class="badge">${x.time}</span><button class="mini" data-del="${x.id}">Delete</button></div></div>`).join("")||empty("Tambahkan slot waktu penting Anda.")};$("#schedule-form").onsubmit=e=>{e.preventDefault();let a=read(K.s,[]);a.push({id:uid(),time:$("#schedule-time").value,title:$("#schedule-title").value,cat:$("#schedule-category").value,note:$("#schedule-note").value});write(K.s,a);e.target.reset();ren()};list.onclick=e=>{let b=e.target.closest("[data-del]");if(!b)return;write(K.s,read(K.s,[]).filter(x=>x.id!==b.dataset.del));ren()};ren()}
function tasks(){const list=$("#task-list"),ren=()=>{let a=read(K.t,[]);list.innerHTML=a.map(x=>`<div class="item task ${x.done?"done":""}"><div class="copy"><strong>${x.title}</strong><p class="muted">${x.note||"Tanpa konteks tambahan"}</p></div><div class="item-actions"><span class="badge priority-${x.priority}">${x.priority}</span><button class="mini" data-toggle="${x.id}">${x.done?"Undo":"Done"}</button><button class="mini" data-del="${x.id}">Delete</button></div></div>`).join("")||empty("Tambahkan task yang benar-benar perlu dikerjakan.");score()};$("#task-form").onsubmit=e=>{e.preventDefault();let a=read(K.t,[]);a.unshift({id:uid(),title:$("#task-title").value,priority:$("#task-priority").value,note:$("#task-note").value,done:false});write(K.t,a);e.target.reset();ren()};list.onclick=e=>{let t=e.target.closest("[data-toggle]"),d=e.target.closest("[data-del]"),a=read(K.t,[]);if(t)a=a.map(x=>x.id===t.dataset.toggle?{...x,done:!x.done}:x);if(d)a=a.filter(x=>x.id!==d.dataset.del);write(K.t,a);ren()};ren()}
function notes(){const list=$("#notes-list"),ren=()=>{let a=read(K.n,[]);list.innerHTML=a.map(x=>`<article class="note"><div class="note-head"><div><strong>${x.title}</strong><p class="muted">${x.date}</p></div><button class="mini" data-del="${x.id}">Delete</button></div><p>${x.body||"-"}</p></article>`).join("")||empty("Gunakan halaman ini untuk quick capture.")};$("#note-form").onsubmit=e=>{e.preventDefault();let a=read(K.n,[]);a.unshift({id:uid(),title:$("#note-title").value,body:$("#note-body").value,date:fDate()});write(K.n,a);e.target.reset();ren()};list.onclick=e=>{let d=e.target.closest("[data-del]");if(!d)return;write(K.n,read(K.n,[]).filter(x=>x.id!==d.dataset.del));ren()};ren()}
function habits(){const list=$("#habit-board"),ren=()=>{let a=read(K.h,[]);list.innerHTML=a.map(x=>`<div class="habit-item"><div class="habit-copy"><strong>${x.name}</strong><p class="muted">${x.target} - ${x.days.filter(Boolean).length}/7 minggu ini</p></div><div class="habit-days">${x.days.map((v,i)=>`<button class="day ${v?"active":""}" data-id="${x.id}" data-day="${i}">${DAYS[i]}</button>`).join("")}</div><button class="mini" data-del="${x.id}">Delete</button></div>`).join("")||empty("Tambahkan rutinitas kecil yang bisa diulang.");score()};$("#habit-form").onsubmit=e=>{e.preventDefault();let a=read(K.h,[]);a.push({id:uid(),name:$("#habit-name").value,target:$("#habit-target").value,days:new Array(7).fill(false)});write(K.h,a);e.target.reset();ren()};list.onclick=e=>{let t=e.target.closest("[data-id][data-day]"),d=e.target.closest("[data-del]"),a=read(K.h,[]);if(t)a=a.map(x=>x.id!==t.dataset.id?x:{...x,days:x.days.map((v,i)=>i===+t.dataset.day?!v:v)});if(d)a=a.filter(x=>x.id!==d.dataset.del);write(K.h,a);ren()};ren()}
function insights(){let t=read(K.t,[]),s=read(K.s,[]),h=read(K.h,[]),p=read(K.p,{done:0}),done=t.filter(x=>x.done).length,open=t.length-done,hit=h.reduce((a,b)=>a+b.days.filter(Boolean).length,0),sc=Math.max(0,Math.min(100,done*14+p.done*10+hit*2-open*3+s.length*2)),msg=sc>=75?"Sistem kerja Anda rapi. Jaga buffer waktu dan review harian.":sc>=45?"Progress berjalan, tapi prioritas dan ritme fokus masih bisa dipertegas.":"Workflow masih longgar. Mulai dari 3 task utama, 1 agenda penting, dan 1 habit inti.",tips=[];if(open>5)tips.push("Task aktif terlalu banyak. Pangkas menjadi 3 prioritas utama.");if(s.length<2)tips.push("Agenda masih minim. Tambahkan time block agar eksekusi lebih konsisten.");if((p.done||0)<2)tips.push("Session fokus masih rendah. Jalankan minimal dua pomodoro.");if(!h.length)tips.push("Belum ada habit tracker. Tambahkan ritual pembuka hari kerja.");if(!tips.length)tips.push("Struktur produktivitas sudah seimbang. Fokus pada kualitas output.");$("#insight-task-done").textContent=done;$("#insight-task-open").textContent=open;$("#insight-events").textContent=s.length;$("#insight-habit-checks").textContent=hit;$("#insight-score").textContent=sc;$("#insight-message").textContent=msg;$("#insight-list").innerHTML=tips.map(x=>`<div class="item"><div class="copy"><strong>Signal</strong><p class="muted">${x}</p></div></div>`).join("")}
document.addEventListener("DOMContentLoaded",()=>{nav();topbar();install();sw();let p=document.body.dataset.page;if(p==="dashboard")dash();if(p==="clock")clockPage();if(p==="stopwatch")stopwatch();if(p==="timer")timer();if(p==="pomodoro")pomodoro();if(p==="schedule")schedule();if(p==="tasks")tasks();if(p==="notes")notes();if(p==="habits")habits();if(p==="insights")insights()});
